// HELPERS
function parseData(d) {
  var keys = _.keys(d[0]);
  return _.map(d, function(d) {
    var o = {};
    _.each(keys, function(k) {
      if( k == 'Agency' )
        o[k] = d[k];
      else if( k == 'Category' )
        o[k] = d[k];
      else if( k == 'Detail' )
        o[k] = d[k];
      else if( k == 'Vendor' )
        o[k] = d[k];
      else
        o[k] = parseFloat(d[k]);
    });
    return o;
  });
}

function getBounds(d, paddingFactor) {
  // Find min and maxes (for the scales)
  paddingFactor = typeof paddingFactor !== 'undefined' ? paddingFactor : 1;

  var keys = _.keys(d[0]), b = {};
  _.each(keys, function(k) {
    b[k] = {};
    _.each(d, function(d) {
      if(isNaN(d[k]))
      {
        return;
      }
      if(b[k].min === undefined || d[k] < b[k].min)
        b[k].min = d[k];
      if(b[k].max === undefined || d[k] > b[k].max)
        b[k].max = d[k];
    });
    b[k].max > 0 ? b[k].max *= paddingFactor : b[k].max /= paddingFactor;
    b[k].min > 0 ? b[k].min /= paddingFactor : b[k].min *= paddingFactor;
  });
  return b;
}

function getCorrelation(xArray, yArray) {
  function sum(m, v) {return m + v;}
  function sumSquares(m, v) {return m + v * v;}
  function filterNaN(m, v, i) {isNaN(v) ?  m.push(i) : m.push(i); return m;}

  // clean the data (because we know that some values are missing)
  var xNaN = _.reduce(xArray, filterNaN , []);
  var yNaN = _.reduce(yArray, filterNaN , []);
  var include = _.intersection(xNaN, yNaN);
  var fX = _.map(include, function(d) {return xArray[d];});
  var fY = _.map(include, function(d) {return yArray[d];});

  var sumX = _.reduce(xArray, sum, 0);
  var sumY = _.reduce(yArray, sum, 0);
  var sumX2 = _.reduce(xArray, sumSquares, 0);
  var sumY2 = _.reduce(yArray, sumSquares, 0);
  var sumXY = _.reduce(xArray, function(m, v, i) {return m + v * yArray[i];}, 0);

  var n = xArray.length;
  var ntor = ( ( sumXY ) - ( sumX * sumY / n) );
  var dtorX = sumX2 - ( sumX * sumX / n);
  var dtorY = sumY2 - ( sumY * sumY / n);
 
  var r = ntor / (Math.sqrt( dtorX * dtorY )); // Pearson ( http://www.stat.wmich.edu/s216/book/node122.html )
  var m = ntor / dtorX; // y = mx + b
  var b = ( sumY - m * sumX ) / n;

  // console.log(r, m, b);
  return {r: r, m: m, b: b};
}

d3.csv('sales.csv', function(data) {

  var xAxis = 'Agency', yAxis = 'Payments';
  var xAxisOptions = ["Agency", "Category", "Detail"]
  // var yAxisOptions = ["Well-being"];
  var descriptions = {
    "Agency" : "Agency",
    "Category" : "Category",
    "Detail" : "Detail"
  };

  var keys = _.keys(data[0]);
  var data = parseData(data);
  var bounds = getBounds(data, 1);

  // SVG AND D3 STUFF
  var svg = d3.select("#chart")
    .append("svg")
    .attr("width", 1000)
    .attr("height", 1000)
    // .call(d3.behavior.zoom().on("zoom", function () {
    // svg.attr("transform", "translate(" + d3.event.translate + ")" + " scale(" + d3.event.scale + ")")
    // }))
    // .append("g")
  
  var xScale, yScale;

  svg.append('g')
    .classed('chart', true)
    .attr('transform', 'translate(80, -60)');
  // console.log(xAxis);
  // Build menus
  d3.select('#x-axis-menu')
    .text("Please select X axis:").classed('lab',true)
    .selectAll('li')
    .data(xAxisOptions)
    .enter()
    .append('li')
    .text(function(d) {return d;})
    .classed('selected', function(d) {
      return d === xAxis;
    })
    .on('click', function(d) {
      xAxis = d;
      // console.log(xAxis);

      updateChart(xAxis);
      updateMenus();
    });
  // console.log(xAxis);
  // d3.select('#y-axis-menu')
  //   .selectAll('li')
  //   .data(yAxisOptions)
  //   .enter()
  //   .append('li')
  //   .text(function(d) {return d;})
  //   .classed('selected', function(d) {
  //     return d === yAxis;
  //   })
  //   .on('click', function(d) {
  //     yAxis = d;
  //     updateChart();
  //     updateMenus();
  //   });

  // Country name
  d3.select('svg g.chart')
    .append('text')
    .attr({'id': 'countryLabel', 'x': 0, 'y': 170})
    .style({'font-size': '30px', 'font-weight': 'bold', 'fill': '#ddd'});

  // Best fit line (to appear behind points)
  d3.select('svg g.chart')
    .append('line')
    .attr('id', 'bestfit');

  // Axis labels
  d3.select('svg g.chart')
    .append('text')
    .attr({'id': 'xLabel', 'x': 400, 'y': 670, 'text-anchor': 'middle'})
    .text(descriptions[xAxis]);

  d3.select('svg g.chart')
    .append('text')
    .attr('transform', 'translate(-60, 330)rotate(-90)')
    .attr({'id': 'yLabel', 'text-anchor': 'middle'})
    .text('Payments');

  // Render points
  // var sF = fData.map(function(d){return [d.State,d.total];});
  var cate = ['BUILDING LEASE PAYMENTS', 
            'COMMUNICATION SERVICE & SUPPLIES', 
            'COMPUTER EQUIPMENT', 
            'DEBT SERVICE', 
            'EQUIPMENT RENTAL & LEASES', 
            'FUEL & UTILITIES', 
            'HOUSEKEEP & JANITOR SERVICES', 
            'MISCELLANEOUS EXPENSES', 
            'MOTORIZED EQUIPMENT', 
            'OFFICE EQUIPMENT', 
            'OTHER EQUIPMENT', 
            'PROFESSIONAL DEVELOPMENT', 
            'PROFESSIONAL SERVICES', 
            'PROGRAM DISTRIBUTIONS', 
            'PROPERTY & IMPROVEMENTS', 
            'REPAIR & MAINTENANCE SERVICES', 
            'SUPPLIES', 
            'TRAVEL'];
  var agen = ['AGRICULTURE', 
            'CONSERVATION', 
            'CORRECTIONS', 
            'ECONOMIC DEVELOPMENT', 
            'ELEMENTARY AND SECONDARY EDUCATION', 
            'HEALTH AND SENIOR SERVICES', 
            'HIGHER EDUCATION', 
            'INSURANCE, FIN INST AND PROF REGISTRATION', 
            'JUDICIARY', 
            'LABOR AND INDUSTRIAL RELATIONS', 
            'LEGISLATURE', 
            'MENTAL HEALTH', 
            'NATURAL RESOURCES', 
            'OFFICE OF ADMINISTRATION', 
            'OFFICE OF ATTORNEY GENERAL', 
            'OFFICE OF GOVERNOR', 
            'OFFICE OF LIEUTENANT GOVERNOR', 
            'OFFICE OF SECRETARY OF STATE', 
            'OFFICE OF STATE AUDITOR', 
            'OFFICE OF STATE TREASURER', 
            'PUBLIC SAFETY', 
            'REVENUE', 
            'SOCIAL SERVICES', 
            'TRANSPORTATION'];
  var det = ["BLDG/STORAGE/STRUCTURE LEASES, CAPITAL","BUILDING/STORAGE/STRUCTURE LEASES, OPER","LAND LEASES, OPERATING","LEASEHOLD IMPROVEMENTS, OPERATING","MEETING ROOM/EXHIBIT SPACE RENTALS","OTHER BUILDING LEASES, OPERATING","PARKING LEASES","REBILL BUILD/STOR SPACE LS","REBILL LEASEHOLD IMPROVE","ANSWERING CHARGES","AUDIO/VIDEO CHARGES","INTERNET CHARGES","NETWORK CIRCUIT LINE CHARGES","OTHER COMMUNICATION CHARGES","REBILLABLE TELECOMM/INTERNET","TELECOMMUNICATION CHARGES","TELECOMMUNICATION SUPPLIES","WIRELESS HAND-HELD DEVICE CHARGES","COMPUTER EQUIPMENT","IT NETWORK & COMMUNICATION EQUIPMENT","MAINFRAME EQUIPMENT","NON MAINFRAME COMPUTER EQUIPMENT","NON-MAINFRAME COMPUTER SOFTWARE","NON MNFRAME SOFTWARE CONSULT&DEVELOPMENT","UNDER THRESHOLD-MAINFRAME COMP SFTWARE","UNDER THRESHOLD-NON MNFRAME COMP SFTWARE","ARBITRAGE REBATE","BOND PRINCIPAL","INTEREST","ISSUANCE RELATED CHARGES","AGRICULTURE/GROUNDS EQUIPMENT RENTALS","AIRCRAFT RENTALS","COMMUNICATION EQUIPMENT LEASES CAPITAL","COMMUNICATION EQUIPMENT RENTALS","HEAVY EQUIPMENT LEASES CAPITAL","HEAVY EQUIPMENT RENTALS","MAINFRAME COMPUTER EQUIP LEASES CAPITAL","MAINFRAME COMPUTER SOFTWARE LEASES","MAINFRAME COMPUTER SOFTWARE RENTALS","NON-MAINFRAME COMPUTER EQUIP LEASES CAP","NON-MAINFRAME COMPUTER SOFTWARE LEASES","OFFICE FURNITURE & EQUIP LEASES CAPITAL","OFFICE FURNITURE & EQUIPMENT RENTALS","OTHER EQUIPMENT LEASES CAPITAL","OTHER EQUIPMENT RENTALS","PRINTING,REPRODUCT&PHOTO EQUIP LEASE CAP","PRINTING,REPRODUCT&PHOTO EQUIP RENTALS","SCIENCE & TECHNOLOGY EQUIP LEASES CAP","SCIENCE & TECHNOLOGY EQUIPMENT RENTALS","SHORT TERM COMPUTER EQUIPMENT RENTALS","VEHICLE LEASES, CAPITAL","VEHICLE RENTALS","ELECTRICITY","FUEL OIL","NATURAL GAS","OTHER FUEL & UTILITIES","PROPANE","REBILLABLE ELECTRIC","REBILLABLE NATURAL GAS","REBILLABLE WATER AND SEWAGE","RENEWABLE ENERGY","WATER & SEWAGE","FIRE EXTINGUISHER SERVICES","GROUNDS MAINTENANCE SERVICES","HOUSEKEEP & JANITOR SERVICES","OTHER HOUSEKEEPING & JANITORIAL SERVICES","PARKING LOT MAINTENANCE SERVICES","REBILLABLE WASTE REMOVAL SERV","REBILL JANITORIAL SERVICES","SNOW REMOVAL SERVICES","WASTE REMOVAL SERVICES","WATER TREATMENT SERVICES","WINDOW WASHING SERVICES","AGENCY PROVIDED FOOD","COPIES OF RECORDS","FUNDING OF IMPREST FUND","INMATE, PATIENT & STUDENT PAYMENTS","INSURANCE & SURETY BOND PREMIUM","INTEREST PAYMENTS","INVESTIGATIVE EXPENSES","LATE PAYMENT PENALTY CHARGE","LOTTERY PRIZES","LOTTERY PRIZES-MERCHANDISE","LOTTERY RETAILER INCENTIVES","LOTTERY RETAIL INCENTIVE-MERCHANDISE","NON-PHYSICAL INJURY LEGAL SETTLEMENTS","OTHER MISCELLANEOUS EXPENSE","OTHER MISCELLANEOUS SERVICES","OTHER REBILLABLE EXPENSES","PERSONAL INJURY LEGAL SETTLEMENTS","PRIZES & AWARDS","PROPERTY DAMAGE SETTLEMENTS","REBILLABLE EQUIPMENT USAGE","REBILLABLE LAB EXPENSES","REBILLABLE LABOR ADDITIVE","REBILLABLE MOTOR POOL COSTS","RELOCATION COSTS/EMPLOYEE","RELOCATION COSTS/OFFICES","AGRICULTURE/GROUNDS EQUIPMENT","BOATS & MOTORS","HEAVY EQUIPMENT","MOTORIZE EQUIPMENT","OTHER MOTORIZED EQUIPMENT","RECREATIONAL VEHICLES","VEHICLES","OFFICE EQUIP &FURNITURE","OFFICE EQUIPMENT","OFFICE FURNITURE","OTHER OFFICE EQUIPMENT","REPRODUCTION & PRINTING EQUIPMENT","AGRICULTURE/GROUNDS MAINT  - NON AUTO","COMMUNICATION EQUIPMENT","CUSTODIAL EQUIPMENT","DURABLE MEDICAL EQUIPMENT","EDUCATIONAL EQUIPMENT","ELECTRONIC EQUIPMENT","EXHIBIT EQUIPMENT","FIXTURES","FOOD SERVICE EQUIPMENT","HOUSEHOLD FURNITURE & EQUIPMENT","LABORATORY EQUIPMENT","LAUNDRY EQUIPMENT","LAW ENFORCEMENT EQUIPMENT","MAILING EQUIPMENT","MECHANICAL EQUIPMENT","MEDICAL & DENTAL EQUIPMENT","OTHER EDUCATIONAL EQUIPMENT","OTHER ELECTRONIC & PHOTOGRAPHIC EQUIP","OTHER EQUIPMENT","OTHER FIXED ASSETS","OTHER FIXED ASSETS-OUTSIDE ENTITIES","OTHER MEDICAL & LABORATORY EQUIPMENT","OTHER SPECIFIC USE EQUIPMENT","OTHER STATIONARY EQUIPMENT","PHOTOGRAPHIC EQUIPMENT","RECREATIONAL EQUIPMENT","TOOLS & SHOP EQUIPMENT","WATER SYSTEM EQUIPMENT","CONVENTION, CONFERENCE & TRAINING FEES","LICENSES AND CERTIFICATIONS","ORGANIZATION MEMBERSHIPS","OTHER PROFESSIONAL DEVELOPMENT","TUITION EXPENSES","ACCOUNTING & AUDITING SERVICES","ADVERTISING SERVICES","AGRICULTURE RELATED SERVICES","ATTORNEY SERVICES","ATTORNEY & SETTLEMENT PAYMENTS","BURIAL SERVICES","COLLECTION SERVICES","CREDIT CARD FEES","EDUCATIONAL HEALTH SERVICES","EDUCATIONAL SERVICES","EXPRESS & FREIGHT SERVICES","FOOD SERVICES","HAULING SERVICES","HAZARD WASTE DISPOSAL SERVICES","HEARING OFFICER SERVICES","IMAGING SERVICES","INFORMATION TECHNOLOGY CONSULTING SERV","INFORMATION TECHNOLOGY OUTSOURCING","INSPECTION SERVICES","LABORATORY SERVICES","LAUNDRY & LINEN SERVICES","LIBRARY SERVICES","MAILING SERVICES","MEDICAL & DENTAL SERVICES","MOVING SERVICES","NON-MEDICAL LABORATORY SERVICES","OTHER BUSINESS SERVICES","OTHER HEALTH SERVICES","OTHER PROFESSIONAL SERVICES","PHOTOGRAPHIC SERVICES","PHYSICAL EXAM SERVICES","PRINTING & BINDING SERVICES","PROFESSIONAL COURT SERVICES","PROFESSIONAL SPEAKER & ENTERTAINER SERV","PROGRAM CONSULTANT SERVICES","PUBLIC RELATIONS SERVICES","REBILLABLE ADVERTISING SERVICE","REBILLABLE LABOR COSTS","REBILLABLE SECURITY SERVICES","REBILLABLE TRAINING SERVICES","REBILL COMPUTER INFO SERV","REBILL EXPR & FREIGHT SERV","REBILL PRINT & BINDING SERV","REHABILITATIVE SERVICES","SECURITY SERVICES","TEMPORARY PERSONNEL SERVICES","VETERINARIAN SERVICES","AGRICULTURE ASSISTANCE PAYMENT","AID EDUC INSTIT & SCHOOL DIST","AID  INSTITUTIONS/INDIVIDUALS","AID TO LOCAL GOVERNMENTS","CLIENT ASSISTANCE SERVICES","CRIME VICTIMS PAYMENTS","DISTRIBUTION  STATE AGENCIES","DISTRIBUTIONS TO CLAIMANTS","EDUCATION ASSIST PAYMENTS","HEALTH ASSIST BENEFITS","HOME & COMMUNITY BASED SERVICES","LAND MGMT PRACTICES INCENTIVES","LOAN DISBURSE OTHER ENTITIES","MEDICAL ASSIST SERVICES","MENTAL HEALTH PAYMNTS-1099 NO","MENTAL HEALTH PAYMNTS-1099 YES","OTHER ASSISTANCE BENEFITS","OTHER ASSISTANCE PAYMENTS","PROGRAM REIMBURSEMENTS","PUBLIC ASSISTANCE PAYMENTS","SECOND INJURY PAYMENTS","UNEMPL WORKER ASSIST PAY","WORKER'S COMP PAYMENTS","APPRAISAL/ADJUSTER SERVICES","ARCHITECT & ENGINEER SERVICES","BUILD/FACILITY RENOVATION & REHAB SERV","BUILDING/FACILITY CONSTRUCTION SERVICES","BUILDING/FACILITY PURCHASES","COMMUNICATIONS INFRASTRUCTURE","DEMOLITION & SITE PREPARATION","INFRASTRUCTURE CONSTRUCTION PAYMENTS","INFRASTRUCTURE MAINTENANCE PAYMENTS","LAND PURCHASE OPTIONS","LAND PURCHASES","LAND SURVEY SERVICES","MAJOR BUILDING/FACILITY REPAIR SERVICES","MINOR REPAIR, MAINT & IMPROVEMENT SERV","OTHER PROPERTY & IMPROVEMENTS","PROJECT MANAGEMENT FEES","PROPERTY & IMPROVEMENTS","SITE IMPROVEMENTS","SITE REPAIR & MAINTENANCE SERVICES","SPECIALIZED SERVICES","AGRICULTURE/GROUNDS EQUIP REPAIR & MAINT","AIRCRAFT REPAIR & MAINTENANCE","BOATS & MOTORS REPAIR & MAINTENANCE","COMMUNICATION EQUIP REPAIR & MAINT","COMPUTER HARDWARE REPAIR & MAINTENANCE","COMPUTER SOFTWARE MAINTENANCE & LICENSES","EDUCATIONAL EQUIP REPAIR & MAINTENANCE","ELECTRICAL REPAIR & MAINTENANCE SERVICES","ELECTRONIC & PHOTO EQUIP REPAIR & MAINT","HEAVY EQUIPMENT REPAIR & MAINTENANCE","LAB & MEDICAL EQUIP REPAIR & MAINTENANCE","MECHANICAL REPAIR & MAINTENANCE SERVICES","OFFICE FURNITURE & EQUIP REPAIR & MAINT","OTHER EQUIPMENT REPAIR & MAINTENANCE","OTHER TRANSPORTATION REPAIR & MAINT","REBILLABLE VEHICLE REPAIR & MAINTENANCE","RECREATIONAL VEHICLES REPAIR & MAINT","SPECIFIC USE EQUIP  REPAIR & MAINTENANCE","TECHNICAL EQUIPMENT REPAIR & MAINTENANCE","VEHICLE REPAIR & MAINTENANCE","AGRICULTURE/GROUNDS SUPPLIES","AIRCRAFT REPAIR SUPPLIES","BUILDING REPAIR SUPPLIES","BURIAL SUPPLIES","CLOTHING SUPPLIES","CUSTODIAL SUPPLIES","EDUCATION SUPPLIES","ELECTRICAL SUPPLIES","ENGINEERING & TECHNICAL SUPPLIES","FOOD & DIETARY SUPPLIES","FOOD SERVICE SUPPLIES","INFORMATION TECHNOLOGY SUPPLIES","LABORATORY SUPPLIES","LAUNDRY & LINEN SUPPLIES","LAW ENFORCEMENT SUPPLIES","LIBRARY MATERIAL & SUPPLIES","MANUFACTURING SUPPLIES","MECHANICAL SUPPLIES","MEDICAL & DENTAL SUPPLIES","MICROFICHE/FILM SUPPLIES","MOTOR FUEL","NOTARY SUPPLIES","OFFICE SUPPLIES","OTHER ADMINISTRATIVE SUPPLIES","OTHER LABORATORY & MEDICAL SUPPLIES","OTHER MERCHANDISING SUPPLIES","OTHER REPAIR & MAINTENANCE SUPP","OTHER RESIDENTIAL SUPPLIES","OTHER SPECIFIC USE SUPPLIES","PERSONAL CARE SUPPLIES","PHARMACEUTICAL DRUGS","PHOTOGRAPHIC SUPPLIES","PLUMBING SUPPLIES","POSTAGE","PRINTING & BINDING SUPPLIES","PROMOTIONAL SUPPLIES","PUBLICATIONS & SUBSCRIPTIONS","REBILLABLE POSTAGE","REBILL INVENT/SUPPLY PURCH","RECOGNITION AWARDS","RECREATIONAL SUPPLIES","RESALE MERCHANDISE","UNIFORM & CLOTHING ALLOWANCE","UNIFORMS & CLOTHING","VACCINES","VEHICLE REPAIR SUPPLIES","VETERINARIAN SUPPLIES","IN-STATE COMMERCIAL TRANSIT","IN-STATE COMMERCIAL TRANSIT - OTHER","IN-STATE LODGING","IN-STATE MEALS","IN-STATE MEALS W/O OVERNIGHT","IN-STATE MILEAGE","IN-STATE USAGE OF STATE VEHICLE","LEGISLATIVE DAILY EXPENSE ALLOWANCE","OTHER IN-STATE TRAVEL EXPENSES","OTHER OUT-OF-STATE TRAVEL EXPENSE","OUT-OF-STATE COMMERCIAL TRANSIT - OTHER","OUT-OF-STATE LODGING","OUT-OF-STATE MEALS","OUT-OF-STATE MEALS W/O OVERNIGHT","OUT-OF-STATE MILEAGE","OUT-OF-ST COMMERCIAL TRANSIT"];
  var ven =["AAA MAILING SERVICE INC","ABC PRINTERS INC","ABSOPURE WATER CO","ACCESS INTERPRETERS LLC","ACCORP INC","ADT SECURITY SERVICES INC","ADVANCED ELECTRIC AND","ADVANCED PAIN CENTER","ADVANTAGE METALS RECYCLING LLC","AGA","AHRENS STEEL & WELD SUP INC","AIRGAS-MID AMERICA INC","AIRGAS-MID SOUTH","AIR MASTERS CORP","AIR SYSTEMS LLC","ALAMAR UNIFORMS","ALARM COMMUNICATION","ALLEN FLOORS INC","ALLIANCE REHAB & MEDICAL EQUIP","ALLIED BEHAVIORAL CONSULTANTS","ALLIED ELECTRONICS-FORT WORTH","ALLIED OIL & SUPPLY INC","ALLIED WASTE SERVICES","ALLMED","ALL SYSTEMS DESIGNED SOLUTIONS","ALPHA REPORTING SERVICE LLC","AL SCHEPPERS MOTOR CO","ALTEC INDUSTRIES INC","ALTERNATIVE OPPORTUNITIES INC","ALTORFER INC","AMAZON COM CREDIT","AMEREN MISSOURI","AMERENUE-ST LOUIS","AMERICAN FIRE AND SAFETY","AMERICAN HOTEL REGISTER CO","AMERICAN RED CROSS","AMERICAN RED CROSS-JEFF CITY","AMERICAN RED CROSS-JEFFERSON C","AMERICAN RED CROSS-KANSAS CITY","AMERICAN RED CROSS-SPRINGFIELD","AMERICAN RED CROSS- ST LOUIS","AMERICAS BEST VALUE INN &","AMERIGAS","AMERIGO","AMERIPRIDE LINEN-SPRINGFIELD","ANDERSON, JOAN","ANIXTER","APAC-MISSOURI INC","APPLIED BIOSYSTEMS","APPLIED INDUSTRIAL","ARAMARK UNIFORM-ST LOUIS","ARCHWAY LIGHTING SUPPLY INC","AREA WIDE INCORPORATED","ARENDT, CYNTHIA K","ARGYLE CATERING COMPANY","ARTS LAWN MOWER SHOP INC","ASH GROVE AGGREGATES INC","ASP ENTERPRISES INC","ASSOCIATION OF GOVERNMENT","ATLAS SECURITY SERVICE INC","ATMOS ENERGY","AT&T","AUDRAIN MEDICAL CENTER","AUTO TIRE & PARTS COMPANY INC","AUTO TIRE & PARTS-IRONTON","AUTO TIRE & PARTS-POPLAR BLUFF","A&W COMMUNICATIONS INC","AYERS OIL CO-CANTON","AZDELL HYDRAULICS & MACHINES","BAKER OBERST, LINDA","BAKER & TAYLOR","BAMVAKAIS, ANTHONY","BANC OF AMERICA LEASING &","BANDANAS BAR-B-Q","BANK OF AMERICA NA","BARNES-JEWISH HOSPITAL","BATES SALES COMPANY","BATTERIES PLUS","BATTERY OUTFITTERS","BAUMAN OIL DISTRIBUTORS INC","BAYMONT INN & SUITES","BEAVER JANITOR SUPPLY","BEERMAN HEATING & COOLING INC","BEE SEEN SIGNS INC","BENNETT-DAVIS, RITA L","BEST WESTERN BIG SPRING LODGE","BEST WESTERN-JEFFERSON CITY","BEYOND TECHNOLOGY","BG SERVICE SOLUTIONS","BIG RIVER OIL CO","BILLS FARM & HOME SUPPLY","BINSWANGER GLASS","B&I TIRE COMPANY INC","BLAKE, ALAN","BLICK ART MATERIALS","BOARD OF POLICE COMMISSIONERS","BOAZ, JOAN T","BOB BARKER COMPANY INC","BOBCAT OF SPRINGFIELD","BOBCAT OF ST LOUIS","BOLIN HYDRAULIC INC","BONNER, SUSAN DETTER","BOONE HOSPITAL CENTER","BOONVILLE AUTO SUPPLY INC","BOWE BELL & HOWELL COMPANY","BOYER LUMBER INC","BOZOIAN, HARRY","BRADS TRUE VALUE HARDWARE","BRADYS FULTON GLASS & PAINT","BRADYS GLASS & PAINT CO INC","BRANDL, ERIKA","BRANNEKY & SONS MERC CO","BRIDGESTONE AMERICAS TIRE","BRIDGEWAY BEHAVIORAL HEALTH","BRISCOE, STEPHANIE","BROADWAY WRECKER LLC","BROSSIER, GREG","BROWNFIELD OIL COMPANY INC","BROWNING HARDWARE","BROWN TRAFFIC PRODUCTS INC","BUCHHEIT ENTERPRISE INC","BUCHHEIT INC","BUD SEWER SERVICE INC","BURLISON, REX","BURRELL BEHAVIORAL HEALTH","BUSCOMM INC","BUTLER SUPPLY-JEFFERSON CITY","BUTLER SUPPLY-ST LOUIS","CABLE DAHMER CHEVROLET","CABOOL TIRES INC","CAMELA CORPORATION","CAMERON LUMBER CO","CAMPBELL, BRANDON D","CAPE ELECTRICAL SUPPLY LLC","CAPE GIRARDEAU PUBLIC SCHOOL","CAPE RADIOLOGY GROUP PC","CAPITAL CITY COURT REPORTING","CAPITAL INSTALLERS INC","CAPITAL MACHINE CO INC","CAPITAL QUARRIES CO INC","CAPITAL REGION MEDICAL CENTER","CAPITAL RUBBER STAMP INC","CAPITAL SAND COMPANY INC","CAPITAL STEEL & DESIGN LLC","CAPITAL SUPPLY COMPANY OF","CAPITOL PLAZA HOTEL","CAPITOL PROJECTS INC","CAR CITY CHRYSLER INC","CARDEN-JESSEN, MELANIE","CARLYLE,  TAMMY J","CARQUEST AUTO PARTS","CARQUEST-CAMERON","CARQUEST-JEFFERSON CITY","CARQUEST-ST JOSEPH","CARRS GOLF CARTS INC","CARTER, PATRICIA","CARTER-WATERS LLC","CASE ELECTRIC LLC","CASH, DONNA J","CATLETT, DON","C&C GROUP","CEE KAY SUPPLY INC","CENTER COURT OFFICE SUPPLY","CENTER FOR BEHAVIORAL MEDICINE","CENTER FOR HEAD INJURY SERVICE","CENTRAL BANK-JEFFERSON CITY","CENTRAL DAIRY COMPANY","CENTRAL METHODIST UNIVERSITY","CENTRAL MISSOURI COMMUNITY","CENTRAL MISSOURI DISTRIBUTING","CENTRAL MISSOURI NEWSPAPERS","CENTRAL MISSOURI PLUMBING CO","CENTRAL RESTAURANT PRODUCTS","CENTRAL SECURITY SYSTEMS","CENTRAL TRAVEL","CENTRAL TRUST BANK","CENTURYLINK","CENTURYTEL","CHAMPION BRANDS LLC","CHANDLER, VANESSA","CHARTER COMMUNICATIONS","CHASECO INC","C&H DISTRIBUTORS LLC","CHEMCO INDUSTRIES INC","CHEMSEARCH","CHEZ MONET","CHIC LUMBER","CHILDRENS MERCY HOSPITAL","CHILDRENS THERAPY CENTER","CHILLICOTHE COMFORT INN &","CINTAS CORPORATION","CINTAS CORPORATION 177","CINTAS CORPORATION NO 2","CINTAS DOCUMENT MANAGEMENT","CITIZENS ELECTRIC CORPORATION","CITIZENS MEMORIAL HOSPITAL","CITY LIGHT GAS & WATER","CITY OF ALBANY","CITY OF AVA-UTILITIES","CITY OF CAMERON","CITY OF CAPE GIRARDEAU","CITY OF CHILLICOTHE MUNICIPAL","CITY OF COLUMBIA","CITY OF COLUMBIA-TREASURER","CITY OF COLUMBIA-UTILITIES","CITY OF EL DORADO SPRINGS","CITY OF FREDERICKTOWN","CITY OF FULTON-CLERK","CITY OF FULTON MUNICIPAL","CITY OF FULTON-MUNICIPAL","CITY OF HANNIBAL","CITY OF HARRISONVILLE","CITY OF HERMANN","CITY OF HOUSTON","CITY OF INDEPENDENCE","CITY OF INDEPENDENCE-UTILITIES","CITY OF JACKSON-TREASURER","CITY OF JEFFERSON","CITY OF JEFFERSON UTILITIES","CITY OF JOPLIN-FINANCE","CITY OF KIRKSVILLE-TREASURER","CITY OF KIRKWOOD","CITY OF LAMAR","CITY OF LEBANON","CITY OF LEXINGTON","CITY OF MACON","CITY OF MACON-MUN UTILITIES","CITY OF MARSHALL-MUNICIPAL","CITY OF MARSHFIELD","CITY OF MARYVILLE-TREASURER","CITY OF MEMPHIS","CITY OF MILAN","CITY OF MONETT","CITY OF NEOSHO-DIRECTOR OF","CITY OF NEVADA","CITY OF PARIS","CITY OF PERRYVILLE","CITY OF POPLAR BLUFF","CITY OF RICH HILL","CITY OF SEDALIA-WATER DEPT","CITY OF SPRINGFIELD-DEPARTMENT","CITY OF SPRINGFIELD-TREASURER","CITY OF ST JOSEPH","CITY OF ST LOUIS-TREASURER","CITY OF ST PETERS","CITY OF TRENTON","CITY OF WASHINGTON","CITY OF WEST PLAINS-UTILITIES","CITY OF WILLOW SPRINGS","CITY UTILITIES OF SPRINGFIELD","CLARION HOTEL & CONFERENCE","CLARK LOCK AND SECURITY CO","CLAWSON TRUCK PARTS & SERVICE","CLAYTON PAPER & DIST INC","CLAYTON, ROBERT","CLERK OF SUPREME COURT","CLERK OF THE SUPREME COURT","COLE COUNTY INDUSTRIES INC","COLEMAN APPLIANCE CENTER","COLUMBIA COLLEGE","COLUMBIA DAILY TRIBUNE","COLUMBIA INTERPRETING SERVICES","COLUMBIA PUBLIC SCHOOL DIST","COMFORT INN-MACON","COMFORT INN-MARYVILLE","COMFORT INN OF WILLOW SPRINGS","COMFORT SUITES-JEFFERSON CITY","COMMUNITY COUNSELING CENTER","COMMUNITY HEALTH CENTER OF","COMMUNITY LUMBER CO","COMPLETE BOOK AND MEDIA SUPPLY","COMPREHENSIVE MENTAL HEALTH","COMTREA FAMILY ASSISTANCE","CONCANNON & JAEGER","COOKS DIRECT INC","COPIES-FYI","COPPEDGE, ANDREW","COTTONWOOD IMPREST FUND","COUNTRY CLUB HOTEL & SPA","COUNTRY INN & SUITES-NEVADA","COUNTY OF ADAIR-TREASURER","COUNTY OF BARRY-TREASURER","COUNTY OF BARTON-TREASURER","COUNTY OF BATES-TREASURER","COUNTY OF BOONE-TREASURER","COUNTY OF BUCHANAN-TREASURER","COUNTY OF BUTLER-TREASURER","COUNTY OF CALLAWAY-TREASURER","COUNTY OF CAMDEN-TREASURER","COUNTY OF CAPE GIRARDEAU","COUNTY OF CASS-TREASURER","COUNTY OF CEDAR-TREASURER","COUNTY OF CHRISTIAN-TREASURER","COUNTY OF CLAY-PUBLIC HEALTH","COUNTY OF CLAY-TREASURER","COUNTY OF COLE-TREASURER","COUNTY OF COOPER-TREASURER","COUNTY OF DEKALB-TREASURER","COUNTY OF DOUGLAS-TREASURER","COUNTY OF DUNKLIN-TREASURER","COUNTY OF FRANKLIN-TREASURER","COUNTY OF GREENE-TREASURER","COUNTY OF GRUNDY HEALTH DEPT","COUNTY OF GRUNDY-TREASURER","COUNTY OF HENRY-TREASURER","COUNTY OF HOWELL-TREASURER","COUNTY OF JACKSON-TREASURER","COUNTY OF JASPER-TREASURER","COUNTY OF JEFFERSON-HEALTH","COUNTY OF JEFFERSON-TREASURER","COUNTY OF JOHNSON-TREASURER","COUNTY OF LACLEDE-TREASURER","COUNTY OF LAFAYETTE-TREASURER","COUNTY OF LAWRENCE-TREASURER","COUNTY OF LINCOLN-TREASURER","COUNTY OF LINN-TREASURER","COUNTY OF MARION-TREASURER","COUNTY OF MORGAN-TREASURER","COUNTY OF NEW MADRID-TREASURER","COUNTY OF NEWTON-TREASURER","COUNTY OF PETTIS-TREASURER","COUNTY OF PHELPS-TREASURER","COUNTY OF PIKE-HEALTH DEPT","COUNTY OF PIKE-TREASURER","COUNTY OF PLATTE-TREASURER","COUNTY OF POLK-TREASURER","COUNTY OF RIPLEY-TREASURER","COUNTY OF SALINE-TREASURER","COUNTY OF ST CHARLES-FINANCE","COUNTY OF STE GENEVIEVE-TREAS","COUNTY OF ST FRANCOIS-TREAS","COUNTY OF ST LOUIS-TREASURER","COUNTY OF STONE-TREASURER","COUNTY OF TANEY-TREASURER","COUNTY OF VERNON-TREASURER","COUNTY OF WARREN-TREASURER","COUNTY OF WEBSTER-TREASURER","COURTYARD BY MARRIOTT COLUMBIA","COVINGTON & BURLING LLP","COX REGIONAL SERVICES","COYS FIRE PROTECTION","CRAFTMASTER HARDWARE CO INC","CRAWFORD SUPPLY CO","CRESCENT PARTS & EQUIPMENT CO","CREST INDUSTRIES INC","CRIDER HEALTH CENTER INC","CRISIS PREVENTION INSTITUTE","CROP PRODUCTION SERVICES","CROSS-MIDWEST TIRE","CROSS REPORTING SERVICE INC","CROWDER COLLEGE","CROWN EQUIP CO","CROWN EQUIPMENT CO","CROWN POWER & EQUIPMENT","C&S BUSINESS SERVICE INC","CULLIGAN OF JEFFERSON CITY","CULLIGAN-SCHAEFER WATER","CULLIGAN WATER COND-COLUMBIA","CUMMINGS, JENNIFER M","CUMMINS MID-SOUTH LLC","CUNNINGHAM, THOMAS J","CURATORS OF THE UNIVERSITY","CUSTOM SCREEN PRINTING","DAILY AMERICAN REPUBLIC","DANDURAND, JOSEPH P ESQ","DANIELS, DOUGLAS R","DANS KEY & LOCK SHOP","DARLING INTERNATIONAL INC","DATA COMM INC","DAVIS, CYNTHIA","DAVIS HOME CENTER","DAYS INN-JEFFERSON CITY","DAYS, RITA HEARD","DEAF INTER-LINK INC","DEAF WAY INTERPRETING SERVICES","DEAN MACHINERY CO","DEEMS FARM EQUIPMENT CO","DEFFENBAUGH DISPOSAL SERVICE","DELTA GROWERS ASSOCIATION","DESOTO ELECTRICAL PRODUCTS","DETTMAN, ELLEN","DIAMOND INTERNATIONAL","DICKEY BUB FARM AND HOME","DICKEY BUB FARM & HOME","DIEHL JR, JOHN J","DIEHMS TIRE SERVICE INC","DIETRICH, NATELLE","DIRECT SUPPLY","DISCOVER VISION CENTERS","DISCOVERY HEALTH RECORD","DISMUKES, THOMAS","DOAN, WILLIAM G","DOBBS TIRE & AUTO CENTERS","DOCUCOPY LLC","DOLLAR GENERAL-NASHVILLE","DONALD FARM & LAWN","DONITAS CAKES & CATERING INC","DOOR CONTROLS INC","DOUBLE CHECK","DOUBLETREE HOTEL AND","DOUBLETREE HOTEL SPRINGFIELD","DRURY INN-COLUMBIA","DRURY INN-FESTUS","DRURY INN-JOPLIN","DRURY INN-KANSAS CITY AIRPORT","DRURY INN-KANSAS CITY STADIUM","DRURY INN POPLAR BLUFF INC","DRURY INN ROLLA","DRURY INN-SIKESTON","DRURY INN-ST LOUIS AIRPORT","DRURY INN-ST LOUIS UNION STA","DRURY INN-ST PETERS","DRURY INN & SUITES ARNOLD","DRURY INN & SUITES-CREVE COEUR","DRURY INN & SUITES-FOREST PARK","DRURY INN & SUITES-HAYTI","DRURY INN & SUITES-SIKESTON","DRURY INN & SUITES-SOUTHWEST","DRURY INN & SUITES-SPRINGFIELD","DRURY INN & SUITES-ST JOSEPH","DRURY INN & SUITES ST LOUIS","DRURY INN & SUITES WESTPORT","DRURY I & S FENTON","DRURY LODGE-CAPE GIRARDEAU","DRURY PLAZA HOTEL-ST LOUIS","DRURY SUITES-CAPE","DRURY UNIVERSITY","DUCKETT TRUCK CENTER INC","DULLE OVERHEAD DOORS INC","DW AUTO & HOME MOBILITY","EARLEY TRACTOR INC","EAST CENTRAL COLLEGE","EASTERS TRUE VALUE","EAST MISSOURI ACTION AGENCY","EAST-WEST GATEWAY COUNCIL","EBE","ECOLAB INC","ECOWATER SYSTEMS INC","ED ROEHR SAFETY PRODUCTS","EDUCATIONAL CONSULTING INC","ELECTRONICS SUPPLY CO INC","ELECTRONIC VIDEO SYSTEMS","ELITE JANITORIAL MAINTENANCE","ELLIOTT DATA SYSTEMS","ELLIS BATTERY SPECIALISTS LLC","ELLIS ELLIS HAMMONS & JOHNSO","EMBARQ MISSOURI INC","EMBASSY SUITES ST CHARLES","EMPIRE DISTRICT ELECTRIC CO","ENGINEERING SURVEYS &","ENTERPRISE","ENTERPRISE GROUP","ENTERPRISE RENT-A-CAR","ENTERPRISE RENTA CAR","ENVIRONMENTAL ENGINEERING INC","ERB EQUIPMENT CO INC","ESSE HEALTH","EUREKA RENTAL LLC","EVERETT QUARRIES CO INC","EWERS TIRES INC","EXECUTIVE HOTEL MANAGEMENT","FABICK AND COMPANY","FABICK POWER SYSTEMS INC","FAMILY CARE HEALTH CENTERS","FAMILY CENTER OF FARMINGTON","FAMILY CENTER OF HARRISONVILLE","FAMILY COUNSELING CENTER","FAMILY COUNSELING CENTER OF MO","FARM EQUIPMENT SALES INC","FARM & HOME OF WARRENSBURG","FARMINGTON CLINIC COMPANY LLC","FARM PLAN","FARM POWER LAWN-LEISURE","FASTENAL CO","FASTENAL COMPANY","FEDERAL EXPRESS","FEDEX KINKOS","FERGUSON ENTERPRISES","FERGUSON MEDICAL GROUP","FERRARI, RICHARD S","FERRELLGAS LP-DENVER","FIRE SAFETY INC","FIRST CALL","FISCHER GLASS","FISHER SCIENTIFIC","FLAGHOUSE INC","FLAG LOFT","FLEET SERVICES","FLETCHALL PIPE & STEEL","FORD HOTEL SUPPLY CO","FORKLIFTS OF CENTRAL MISSOURI","FRANCE FIRE EXTINGUISHER CO","FRED WEBER INC","FREEMAN HEALTH SYSTEM","FRENCH GERLEMAN ELECTRIC CO","FRIEL, MELISSA","FRIGA CONSTRUCTION COMPANY INC","FULL SPECTRUM PHOTO","FULTON AUTO SUPPLY INC","FULTON RENTALS LLC","FUNDERBURK, DOUG","GALLIMORE, TIMOTHY","GALLS","GALLS AN ARAMARK COMPANY LLC","GAMBLIN LUMBER CO","GASSNER, JOE","GAYLORD BROTHERS","G&D COMMUNICATIONS INC","GEHRKE, JUDY","GENERAL PARTS LLC","GIFFORD LUMBER CO INC","GLASS, SUSAN","GLOBAL EQUIPMENT COMPANY","GOODMAN, JACK","GOODYEAR AUTO CENTER-ATLANTA","GOODYEAR TIRE & RUBBER-AKRON","GOODYEAR TIRE & RUBBER-ATLANTA","GORE PERRY REPORTING & VIDEO","GRACE HILL NEIGHBORHOOD HEALTH","GRAINGER","GRAND RIVER MUTUAL TELEPHONE","GRANDVIEW NURSERIES INC","GRAVES MENU MAKER FOODS","GRAYBAR ELECTRIC COMPANY INC","GREAT CENTRAL LUMBER CO","GREEN, SUSAN PRITCHARD","GREENVILLE SAW SHOP","GRINER & SCHMITZ INC","GROSS, RANDY S","GUARDIAN MEDICAL LOGISTICS","GW VAN KEPPEL CO","HACH COMPANY","HA COVER & SON LUMBER CO","HADLEY, TRACI","HAGLER, JON M","HAMPTON INN-CLINTON","HAMPTON INN-JEFFERSON CITY","HAMPTON INN & SUITES","HANDY MAN TRUE VALUE HARDWARE","HANGER PROSTHETICS & ORTHO INC","HANGER PROSTHETICS & ORTHOTICS","HANNEKE HARDWARE & INDUSTRIAL","HANNIBAL BOARD OF PUBLIC","HANNIBAL REGIONAL HOSPITAL","HARDEN, DENNIS DEAN","HAROLD G BUTZER INC","HARRIS STOWE STATE UNIVERSITY","HARRY COOPER SUPPLY","HASLAG, HEATHER","HASLER","HAWTHORNE PSYC IMPREST FUND","HAWTHORN FOUNDATION","HD SUPPLY WATERWORKS","HEALTHCARE EQUIPMENT & SUPPLY","HEALTHPORT TECHNOLOGIES LLC","HEARTLAND FARM & LAWN","HEARTLAND REGIONAL MEDICAL","HEINTZ, JENNIFER","HEISLER, SUSAN J","HENRY COUNTY WATER CO","HENRY SCHEIN INC","HERITAGE-CRYSTAL CLEAN LLC","HERITAGE FOOD SERVICE","HERTZ EQUIPMENT RENTAL CORP","HEWLETT-PACKARD","H&G SALES INC","HIAWATHA IMPLEMENT CO","HIGGINSVILLE ADVANCE","HILLYARD","HILLYARD FLOOR CARE SUPPLY","HILTI INC","HILTON GARDEN INN-COLUMBIA","HILTON GARDEN INN-INDEPENDENCE","HILTON ST LOUIS AT THE","HIRSCH FEED & FARM SUPPLY","HOBART","HOBART SALES & SERVICE","HOBBY LOBBY STORES INC","HOLIDAY INN","HOLIDAY INN EXPRESS","HOLIDAY INN EXPRESS-HANNIBAL","HOLIDAY INN EXPRESS-JEFFERSON","HOLIDAY INN EXPRESS-KIRKSVILLE","HOLIDAY INN EXPRESS-SALEM","HOLIDAY INN EXPRESS-WEST PLAIN","HOLIDAY INN-FARMINGTON","HOLIDAY INN SELECT-EXEC CTR","HOME DEPOT CREDIT SERVICES","HOMESTORE","HOMETOWN HARDWARE","HOMETOWN HEARING & AUDIOLOGY","HOOVER BROTHERS FARMS INC","HOSE, JOHN H","HOSKINS, JOHN D","HOTEL DEVILLE LLC","HOTEL GOVERNOR OF JEFFERSON CI","HOWELL-OREGON ELECTRIC","HUBER & ASSOCIATES INC","HUBERT COMPANY","HUMANE RESTRAINT COMPANY INC","HY-VEE-JEFFERSON CITY","HY-VEE-WEST DES MOINES","IBM CORPORATION","ICE-MASTERS INC","IDN H HOFFMAN - ST LOUIS","IKON OFFICE SOLUTIONS","IKON OFFICE SOLUTIONS-COLUMBIA","IKON OFFICE SOLUTIONS-DALLAS","ILER ENTERPRISES LLC","IMAGE TECHNOLOGIES OF MISSOURI","INDEPENDENT ELECTRIC MACHINERY","INDUSTRIAL SOAP CO","INN AT GRAND GLAIZE","INSTITUTE OF INTERNAL AUDITORS","INTERCOUNTY ELECTRIC","INTERNATIONAL ASSOCIATION OF","INTERNATIONAL INSTITUTE OF","INTERNATIONAL LANGUAGE CENTER","INTERSTATE BATTERY SYSTEM OF","INTOXIMETERS INC","ISENHOWER LUMBER CO","ISG TECHNOLOGY INC","ITT TECHNICAL INSTITUTE","JACK HORNER MACHINERY &","JACKSON LAWN EQUIPMENT","JACKS SPORTING GOODS &","JACQUINOT, THOMAS J","JAMES, WILLIAM H","JAMIESON MACHINE INDUSTRIAL","JAY KEY SERVICE INC","JCI INDUSTRIES","JC INDUSTRIAL SUPPLY","JCS WIRELESS","JEFFERSON CITY AUTO SUPPLY","JEFFERSON CITY FLYING SERVICE","JEFFERSON CITY LANDFILL LLC","JEFFERSON CITY MEDICAL GROUP","JEFFERSON CITY OIL CO INC","JEFFERSON CITY SCHOOL DISTRICT","JEFFERSON CITY WINNELSON CO","JEFFERSON COLLEGE","JEFFERSON MEMORIAL HOSPITAL","JIMS TIRE SERVICE INC","JOE MACHENS FORD","JOHN DEERE GOVERNMENT SALES","JOHN FABICK TRACTOR CO","JOHN HENRY FOSTER CO INC","JOHNSON CONTROLS","JOHNSON COUNTY COMMUNITY","JOHNSTONE SUPPLY","JOHNSTONE SUPPLY OF SPFD","JOPLIN FIRE PROTECTION CO INC","JOPLIN SUPPLY CO","JP PROMOTIONS","JUNIOR COLLEGE DISTRICT OF","KANSAS CITY COMMUNITY CENTER","KANSAS CITY MISSOURI PUBLIC","KANSAS CITY POWER & LIGHT CO","KANSAS CITY STAR","KANSAS CITY STAR CO","KC BOBCAT","KCMO WATER SERVICES DEPT","KCP&L GREATER MISSOURI","KEITH, KEVIN L","KELLER FIRE & SAFETY INC","KELLOGG BROWN & ROOT SERVICES","KELLY, CATHY R","KENCO FIRE EQUIPMENT","KENNETT BOARD OF PUBLIC WORKS","KENNEY, ROBERT S","KENTON BROTHERS INC","KERNS, LESLIE","KEY REFRIGERATION","KIRKSVILLE DAILY EXPRESS","KIRKSVILLE FARM & HOME SUPPLY","KMART-BRIDGETON","KMART-CAPE GIRARDEAU","KMART-FLORISSANT","KMART-INDEPENDENCE","KMART-KANSAS CITY","KMART-SPRINGFIELD","KMART-ST JOSEPH","KMART-ST LOUIS","KNAPHEIDE TRUCK EQUIPMENT CO","KOECHNER MFG CO INC","KOERKENMEIER, TERESA M","KONICA MINOLTA BUSINESS","KOPP, TAMARA A","KORSMEYER FIRE PROTECTION","KRC ENTERPRISES","L-1 ENROLLMENT SERVICES","LAB SAFETY SUPPLY INC","LACLEDE ELECTRIC COOPERATIVE","LACLEDE GAS CO","LACLEDE GAS CO CASHIER","LACROSSE LUMBER CO","LACROSSE LUMBER COMPANY","LARSIGNS ENGRAVING","LARSON FARM & LAWN INC","LAUF EQUIPMENT CO INC","LAWSON PRODUCTS INC","LAWSON, TINA K","LAYTON, JAMES","LEAD BELT MATERIALS CO INC","LEARFIELD COMMUNICATIONS INC","LEE MACHINE SHOP LLC","LEES LAWN CARE & EQUIPMENT","LEGAL DIRECTORIES PUBLISHING","LEON UNIFORM CO INC","LEO OLAUGHLIN INC","LEWIS & ASSOCIATES LTD","LEXISNEXIS","LEXIS NEXIS","LIBERAL BUILDING CENTER","LIBERTY HOSPITAL","LIFELOC TECHNOLOGIES INC","LIFE SKILLS FOUNDATION","LINCOLN UNIVERSITY-CONTROLLER","LINCOLN UNIVERSITY-CONTROLLERS","LINEAGE","LINN STATE TECHNICAL COLLEGE","LINWELD","LINWELD INC","LI, YAN","LOCKTON COMPANIES LLC","LODGE OF FOUR SEASONS","LOMAS CONSTRUCTION SERVICES","LOOMIS BROTHERS EQUIPMENT CO","LOWES","LOWES-ATLANTA","LOWES-FARMINGTON","LOWES-JEFFERSON CITY","LOWES-OSAGE BEACH","LOWES-SPRINGFIELD","LUBY EQUIPMENT SERVICES","LUEBBERING OIL CO","LUETKEMEYER SIGNS","LUMPKINS, DEBRA K","LYSKOWSKI, PETER A","MACON ELECTRIC COOP","MACON MUNICIPAL UTILITES","MADISONS CAFE","MAGRUDER LIMESTONE CO INC","MALEY, RANDALL","MARBLE GRAPHICS INC","MARKS MOBILE GLASS INC","MARKS MOBILE GLASS INC 3","MARK TWAIN BEHAVIORAL HEALTH","MARMIC FIRE AND SAFETY","MARMIC FIRE & SAFETY CO","MARSHALL HOMESTORE","MARSHALL MUNICIPAL UTILITIES","MARSHALL SERVICE COMPANY","MARTINS TRUE VALUE HARDWARE","MASCHECK, JENNIE","MATHESON-LINWELD","MATHESON TRI-GAS INC","MATTHEW BENDER & CO INC","MAVERICK GLASS INC","M-B COMPANIES INC","MCALISTERS DELI","MCCUNE BROOKS HOSPITAL","MCDONALD, THOMAS","MCINTIRE LUMBER CO","MCKESSON MEDICAL SUPPLY INC","MCKESSON MEDICAL-SURGICAL","MCKNIGHT TIRE","MCMANUS, JOHN K","MCMASTER-CARR","MCMASTER-CARR SUPPLY CO","MEDIACOM","MEDICAL WEST HEALTHCARE CENTER","MEDLINE INDUSTRIES INC","MEEKS-POPLAR BLUFF","MEGA DISTRIBUTORS","MEGGITT TRAINING SYSTEMS INC","MENARDS","MERCURY MARINE","MERCY MEDICAL GROUP","MERS MISSOURI GOODWILL IND","METAL CULVERTS INC","METALWELD INC","METRO BUSINESS COLLEGE","METRO OFFICE SOLUTIONS INC","METROPOLITAN COMMUNITY COLLEGE","METROPOLITAN ST LOUIS SEWER","METRO ST LOUIS PSY IMPREST FND","MEYER ELECTRIC CO","MFA AGRI SERVICES-MACON","MFA OIL CO-BROOKFIELD","MFA OIL CO-CHILLICOTHE","MFA OIL CO-COLUMBIA","MFA OIL CO-FULTON","MFA OIL CO-JASPER","MFA OIL CO-MARSHALL","MFA OIL CO-STE GENEVIEVE","MFA OIL CO-ST JOSEPH","MID-AMERICA REGIONAL COUNCIL","MID-CITY LUMBER CO LTD","MIDLAND EMPIRE RESOURCES","MID STATE PETROLEUM EQUIPMENT","MIDWEST ADVERTISING","MIDWEST ELECTRONIC SYSTEMS","MIDWEST HARDWARE & RENTAL INC","MIDWEST LITIGATION SERVICES","MIDWEST MOBILE RADIO SERVICE","MIDWEST PAGING","MIKE KEHOE FORD INC","MIKES TIRE SERVICE","MILBRADT LAWN EQUIPMENT CO","MILLS IRON & SUPPLY CO","MINERAL AREA COLLEGE","MINERAL AREA JUNIOR COLLEGE","MINERAL AREA OFFICE SUPPLY","MINERAL AREA OVERHEAD DOOR INC","MINNICK SUPPLY  CO","MISCELLANEOUS VENDOR PAYMENTS","MISSOURI AMERICAN WATER","MISSOURI ASSOCIATION FOR","MISSOURI ASSOCIATION OF","MISSOURI ASSOCIATION OF PUBLIC","MISSOURI ASSOC OF COUNTIES","MISSOURI BAR","MISSOURI BAR CLE DEPARTMENT","MISSOURI BUILDERS SERVICE INC","MISSOURI COALITION AGAINST","MISSOURI DELTA MEDICAL CTR","MISSOURI GAS ENERGY","MISSOURI INSTITUTE OF MENTAL","MISSOURI JUVENILE JUSTICE","MISSOURI LEGISLATIVE SERVICE","MISSOURI LIBRARY NETWORK CORP","MISSOURI NATURAL GAS COMPANY","MISSOURI POLICE CHIEFS ASSN","MISSOURI PRESS ASSOCIATION","MISSOURI PRESS CLIPPING BUREAU","MISSOURI PRESS SERVICE INC","MISSOURI REHABILITATION CENTER","MISSOURI SCHOOL BOARD ASSN","MISSOURI SHERIFFS ASSN","MISSOURI SOUTHERN STATE","MISSOURI STATE TROOPERS","MISSOURI STATE UNIVERSITY","MISSOURI WESTERN STATE UNIV","MITEL TECHNOLOGIES INC","MK SUPPLIES","M&M GOLF CARS LLC","MOBERLY AREA COMMUNITY COLLEGE","MOBIL FONE","MO BLVD TOUCHLESS CAR WASH","MODERN COMMUNICATIONS INC","MODERN FARM EQUIPMENT CO INC","MODERN FIRE SAFETY LLC","MONTAUK  RESORT LLC","MOORE EQUIPMENT CO","MOORE MEDICAL CORP","MOORE MEDICAL LLC","MOORE, RICHARD W","MORELAND, CHARLES DOUGLAS","MORGAN, JEREMIAH J","MORPHOTRAK INC","MORRIS & DICKSON CO LLC","MORRIS, JAMES","MORROW & SONS","MORROW TIRE SUPPLY INC","MORSE WATCHMANS INC","MO STATE TROOPERS ASSOC-MSTA","MO UNIV SCIENCE & TECHNOLOGY","MOUSER ELECTRONICS","MSC INDUSTRIAL SUPPLY CO","MU CONFERENCE OFFICE","MUELLER MACHINE WORKS","MUELLER PLUMBING & HEATING","MURPHY TRACTOR & EQUIPMENT CO","NAMI OF MISSOURI","NANCE, MARK","NAPA","NASCO","NATIONAL ASSOCIATION OF","NATIONAL ASSOCIATION OF STATE","NATIONAL FASTENER CORP","NATIONAL FIRE PROTECTION ASSOC","NATIONWIDE BUILDING","NAVISTAR INC-FLEET CHARGE","NCS PEARSON INC","NEGWER MATERIALS INC","NEHRING, LESLIE A","NEOPOST USA INC","NETCO INC","NEUMAYER EQUIPMENT INC","NEVADA DAILY MAIL","NEVADA REGIONAL MEDICAL CENTER","NEWS TRIBUNE","NFPA","NICASTRO, CHRIS L","NIEC, DANIEL C","NIETZEL, MICHAEL T","NORRIS AGGREGATE PRODUCTS","NORTH CENTRAL MISSOURI COLLEGE","NORTHERN TOOL & EQUIPMENT","NORTH KANSAS CITY HOSPITAL","NORTHWEST IMPLEMENT INC","NORTHWEST MISSOURI STATE","NOTARY PUBLIC UNDERWRITERS","NPG NEWSPAPERS INC","NU WAY CONCRETE FORMS","NU WAY CONCRETE FORMS INC","NU WAY WENTZVILLE LLC","OCCUPATIONAL HEALTH CENTERS OF","OESTERLY, ANGELA J","OFFICE DEPOT-CHICAGO","OFFICE DEPOT-CINCINNATI","OFFICE DEPOT INC","OFFICEMAX","OFFICEMAX INCORPORATED","OMB POLICE SUPPLY","ORACLE AMERICA INC","OREILLY AUTOMOTIVE PARTS","OREILLY AUTO PARTS","OREILLY AUTO PARTS-SPRINGFLD","ORSCHELN FARM & HOME LLC","OSULLIVAN, LAURA E","OVERHEAD DOOR CO OF ST JOSEPH","OVERHEAD DOOR CO OF ST LOUIS","OZ ARC GAS EQUIPMENT & SUPPLY","OZARK CENTER","OZARKS COMMUNITY HOSPITAL","OZARKS MEDICAL CENTER","OZARKS TECHNICAL COMM COLLEGE","OZARKS TECHNICAL COMMUNITY","PACER SERVICE CENTER","PACKS DO IT CENTER","PAGE AND BROWN CONVENTION","PALMER, VERONICA","PARAQUAD INC","PARDALOS, ANN","PARIS HARDWARE & SUPPLY","PARKLAND HEALTH CENTER","PATHWAYS COMMUNITY BEHAVIORAL","PAVYER PRINTING MACHINE WORKS","PBSH LIMITED LC","PBSH LIMITED L C","PEARSON EDUCATION","PE JEPSON LUMBER CO","PENDLETON, SCOTT BRIAN","PERKINS LUMBER CO INC","PERRY WINKLE HOSPITALITY","PETERS HEATING & AC INC","PETERSON GROUP","PHELPS COUNTY REG MED CENTER","PHILIPS & COMPANY","PIC SUPPLY CO","PIKE COUNTY MEMORIAL HOSPITAL","PIPE PLUS INC","PITNEY BOWES","PITNEY BOWES INC","PITNEY BOWES-LOUISVILLE","PITNEY-BOWES-LOUISVILLE","PITNEY BOWES-LOUISVILLE CREDIT","PITNEY BOWES RESERVE ACCOUNT","PITNEY BOWES-RESERVE ACCOUNT","PLAZA TIRE SERVICE INC","PLUMMERS HOW-TO-STORE","POCAHONTAS LUMBER & HARDWARE","POLSINELLI SHUGHART PC","POPPS OUTDOOR EQUIPMENT INC","PORTERS BUILDING CENTERS INC","POSTMASTER OF JEFFERSON CITY","POSTMASTER OF SPRINGFIELD","PRAIRIE FARMS DAIRY INC","PRAXAIR DISTRIBUTION INC","PRECISION ART","PREFERRED FAMILY HEALTH CARE","PREMIER KNOWLEDGE SOLUTIONS","PREMIER PAPER & PACKAGING INC","PRESLEY SALES & SERVICE INC","PRESSTEK INC","PRESTO-X LLC","PRITCHARD, CHRISTOPHER J","PROCUREMENT CARD PAYMENT","PROMARK SOLUTIONS LLC","PROREHAB PC","PROSPERITY CLEANING","PROST BUILDERS INC","PROTECTED (PUBLIC SAFETY)","PSYCH CARE CONSULTANTS","PSYCH CARE CONSULTANTS LLC","PUBLIC WATER SUPPLY DISTRICT 1","PUBLIC WATER SUPPLY DISTRICT 2","PUBLIC WATER SUPPLY DISTRICT 3","PUBLIC WATER SUPPLY DISTRICT 4","PUCKETT, DONNA","PURCELL TIRE CO-ST LOUIS","PURCELL TIRE & RUBBER-ST LOUIS","PURCHASE RECORDS DESTRUCTION","PUTNAM CHEVROLET-PONTIAC INC","QUALITY INN","QUALITY INN & SUITES","QUARTERMASTER","QUINN LUMBER COMPANY","RABEN TIRE CO INC","RABEN TIRE COMPANY","RACE BROS FARM SUPPLY INC","RACE BROTHERS- CARTHAGE","RADIO COMM","RADIO SHACK - DALLAS","RAGDON CORP","RAMADA OASIS CONVENTION CENTER","RAMPART SECURITY","RED CROSS PHARMACY INC","REED & REED LUMBER CO INC","REEVES-WIEDEMAN COMPANY","REGAL PLASTIC SUPPLY CO","REHABILITATION INSTITUTE","REHAGEN, JOHN F","REINHOLD ELECTRIC INC","REJIS COMMISSION","RELIABLE CHEVROLET","REMI GROUP LLC","RESIDENCE INN BY MARRIOTT","RIBACK SUPPLY CO INC","RICHARD A HOWERTON PROPERTIES","RILEY CHEVROLET INC","RILEYS TIRE SERVICE","RINNES TIRE SERVICE","RIS PAPER COMPANY","RITCHIE, SAMUEL D","RJ HECHLER HARDWARE  INC","RJ KOOL COMPANY","RKV TECHNOLOGIES INC","ROARING RIVER INN","ROBERTS-JUDSON LUMBER CO","ROBEY BUILDING SUPPLY","ROCKHURST COLLEGE OF","ROHLFING, ALAN","ROLAND MACHINERY COMPANY","ROLLA MUNICIPAL UTILITIES","RONS TIRE SERVICE","ROSE INTERNATIONAL","ROYAL PAPERS INC","RP LUMBER COMPANY INC","R&R STORES INC","RSC EQUIPMENT RENTAL","SAFETY-KLEEN COLUMBIA","SAFETY-KLEEN DALLAS","SALLY BEAUTY SUPPLY","SAMCO BUSINESS PRODUCTS","SAMMONS PRESTON","SAMPLE, WYATT R","SAMS JANITORIAL SERVICE","SANFORD-BROWN COLLEGE","SAVERINO SAFE & LOCK COMPANY","SAWYER MAILING SYSTEMS","SAWYER TIRE INC","SCANTRON CORPORATION","SC ELECTRIC INC","SCHAEFER WATER CENTERS","SCHATZ, CHAD CECIL","SCHEPKER PARTS SUPPLY","SCHERR, KEVIN","SCHINDLER ELEVATOR CORP","SCHNEIDER ELECTRIC CO INC","SCHOOL DISTRICT OF","SCHOOL SPECIALITY EDUCATION","SCHRIEFERS OFFICE EQUIPMENT","SCHULTE'S FRESH FOODS","SCHULTE, TIMOTHY","SCHWEISSGUTH BROS INC","SCI ENGINEERING INC","SCOTT, VICTORIA","SCRUGGS LUMBER CO","SECURITY EQUIPMENT SUPPLY","SEDALIA DEMOCRAT","SEDALIA STEEL SUPPLY INC","SEILER INSTRUMENT & MFG CO INC","SHAFER KLINE & WARREN INC","SHAUGHNESSY PAPER CO","SHEPHERD, ERIC","SHERATON CLAYTON PLAZA","SHERWIN-WILLIAMS-CRYSTAL CITY","SHERWIN-WILLIAMS-FARMINGTON","SHERWIN-WILLIAMS-JEFFERSON CTY","SHERWIN-WILLIAMS-ST LOUIS","S&H FARM SUPPLY INC","SHIMADZU SCIENTIFIC INSTRUMENT","SHOAL CREEK DISTRIBUTING CO","SHRED-IT","SIEMENS INDUSTRY INC","SI FUNERAL SERVICES","SIKESTON R-6 SCHOOLS","SIMPLEXGRINNELL LP","SITTON, STEVEN D","SJ SMITH COMPANY INC","SLACK, ANNETTE E","SLUSHER INC","SMART BUSINESS PRODUCTS","SMITH PAPER & JANITOR SUPPLY","SOCIAL SECURITY ADMINISTRATION","SOCIETY FOR HUMAN RESOURCE","SOCIETY OF GOVERNMENT MEETING","SONNYS SOLID WASTE SERVICE INC","SOUTHEAST COOPERATIVE SERVICE","SOUTHEAST MISSOURI HOSPITAL","SOUTHEAST MISSOURI STATE UNIV","SOUTHERN ILLINOIS UNIVERSITY","SOUTHWEST BAPTIST UNIVERSITY","SPACEWALKER INC","SPARKS, DOLORES","SPECIAL SCHOOL DISTRICT OF","SPRINGFIELD NEUROLOGICAL AND","SPRINGFIELD NEWS-LEADER","S&S ELECTRIC MOTOR SERVICE","SSM ST MARYS HEALTH CENTER","S&S WORLDWIDE INC","ST ALEXIUS HOSPITAL CORP 1","STANLEY CONVERGENT SECURITY","STANLEY SECURITY SOLUTIONS INC","STAPLES ADVANTAGE","STAPLES CONTRACT &","STAPLES CONTRACT & COMMERCIAL","STAPLES CREDIT PLAN","STARK, DANIEL A.","STATE FAIR COMMUNITY COLLEGE","STATE INDUSTRIAL PRODUCTS","ST CHARLES COMMUNITY COLLEGE","STERICYCLE INC","STEWART CONCRETE PRODUCTS","ST FRANCIS HOSPITAL","ST FRANCIS MEDICAL CENTER","ST FRANCOIS COUNTY HEALTH","ST JOHNS CLINIC INC","ST JOHNS HOSPITAL-AURORA","ST JOHNS MERCY HOSPITAL","ST JOHNS MERCY MEDICAL CENTER","ST JOHNS REGIONAL HEALTH CTR","ST JOSEPH TRACTOR INC","ST LOUIS AMERICAN NEWSPAPER","ST LOUIS BOILER SUPPLY CO","ST LOUIS BUSINESS JOURNAL","ST LOUIS CHILDRENS HOSPITAL","ST LOUIS COMMUNITY COLLEGE","ST LOUIS POST DISPATCH","ST LOUIS PSY REHB IMPREST FUND","ST LOUIS UNIVERSITY","ST MARYS HEALTH CENTER","ST MARYS OCCUPATIONAL","STODDARD EQUIPMENT CO","STOGSDILL, PRESTON","STOKES, CURTIS R","STONEY CREEK INN OF COLUMBIA","SUBSCRIPTION SERVICES","SUCCESSLINK","SUMMIT MAILING & SHIPPING","SUPER 8 MOTEL-BETHANY","SUPERCO SPECIALTY PRODUCTS","SUR-GRO FINANCE INC","SUTHERLAND BUILDING MATERIAL","SUTHERLAND LUMBER","SUTHERLAND LUMBER CENTRAL LLC","SWAN, KATHLEEN","SYDENSTRICKER FARM & LAWN INC","SYDENSTRICKER IMPLEMENT CO","SYNERGY SERVICES INC","TALLGRASS TECHNOLOGIES","TAN-TAR-A","TCI TIRE CENTERS","TCR","TECH ELECTRONICS INC","T&E COMPANY INC","TEEL MECHANICAL SERVICE","TERMINAL SUPPLY CO","TERMINIX PROCESSING CENTER","TESON, LARRY","TESSCO INCORPORATED","TETRA TECH INC","TEXAS COUNTY MEMORIAL HOSPITAL","THERMAL COMPONENTS CO","THOMAS, PAM","THOMPSON, LINDA","THOMPSON MANAGEMENT GROUP LLC","THREE RIVERS COLLEGE","TIGER COURT REPORTING LLC","TIGER DIRECT INC","TIRE CENTERS LLC","TITAN INDUSTRIAL CHEMICALS LLC","TODDS TIRE SERVICE","TOSHIBA AMERICA BUSINESS","TOSHIBA BUSINESS SOLUTIONS INC","TOUCHPOINT AUTISM SERVICES INC","TRADITION INN","TRAFFIC CONTROL CORPORATION","TRANE COMPANY","TRENTON HARDWARE STORE LLC","TRI-COUNTY COMMUNITY MENTAL","TRI-COUNTY MENTAL HEALTH SVCS","TRI-STATE CONSTRUCTION","TRUMAN HOTEL & CONFERENCE","TRUMAN MEDICAL CENTER-HOSPITAL","TRUMAN MEDICAL CENTER INC","TRUMAN STATE UNIVERSITY","T&S TIRE","TUNKS, TIM","TURABELIDZE, GEORGE","TURNBOUGH BUILDING SUPPLY INC","TYLERS LOCK & KEY SERVICE INC","ULINE SHIPPING SUPPLY","UMB BANK","UNITED CEREBRAL PALSY","UNITED PARCEL SERVICE","UNITED RENTALS NORTH AMERICA","UNITED SEATING AND MOBILITY","UNITED STATES POSTAL SERVICE","UNITED STATES TREASURY","UNITHERM INC","UNIVERSITY OF CENTRAL MISSOURI","UNIVERSITY OF KANSAS","UNIVERSITY OF MISSOURI","UNIVERSITY OF MISSOURI-KC","UNIVERSITY OF MO-COLUMBIA","UNIVERSITY OF MO-KANSAS CITY","UNIVERSITY OF MO-ST LOUIS","UNIVERSITY PHYSICIANS","UNIVERSITY PLAZA HOTEL &","USA MOBILITY WIRELESS INC","US BANK","US FOODSERVICE","US FOOD SERVICE INC","US FOODSERVICE INC","US GEOLOGICAL SURVEY","US RENTS IT","US WATER-LEXINGTON MO INC","UTTS GOLF CARS SALES INC","UZ ENGINEERED PRODUCTS","VALUE TIRE CENTER","VANCE BROTHERS INC","VANDIVER 1500 LLC","VAN KEPPEL CO","VATTEROTT COLLEGE","VEOLIA ES SOLID WASTE","VEOLIA ES SOLID WASTE MIDWEST","VICTOR L PHILLIPS CO","VIKING-CIVES MIDWEST INC","VOGT, MICHAEL","VOSS LIGHTING","VWR INTERNATIONAL LLC","WAGGONER HOME CENTER LLC","WALDINGER CORP","WALDRON, MICHELLE E","WALK, BART","WALL STREET JOURNAL","WAL-MART COMMUNITY","WASHINGTON UNIVERSITY","WASHINGTON UNIVERSITY SHARED","WASHINGTON UNIV SCHOOL OF MED","WASTE REMEDIES LLC","WATERWORK SPECIALTIES INC","WATKINS TRUE VALUE HARDWARE","WAYNESVILLE R VI","WCA WASTE SYSTEMS","WEBER COMMUNICATIONS LLC","WEBER FIRE & SAFETY EQUIP CO","WEBSTER UNIVERSITY","WELLS IMPLEMENT INC","WELLS, MICHAEL","WEST BROTHERS CHRYSLER","WEST CENTRAL MO COMM ACT AGNCY","WESTERN EXTRALITE CO","WESTERN MO MEDICAL CENTER","WESTERN MO MHC IMPREST FUND","WEST GROUP PAYMENT CENTER","WESTLAKE ACE HARDWARE-KC","WESTLAKE ACE HARDWARE-K C","WESTPORT POOL INC","WHEELER, JANET E","WHELEN ENGINEERING COMPANY","WHIPPLE, PEGGY A","WIESE PLANNING & ENGINEERING","WILDWOOD REAL ESTATE CO INC","WILLIAMS, JIMMY L","WILSON TIRE","WINDSTREAM CORPORATION","WIRELESS USA INC","WISE EL SANTO","WOESTMAN PROPERTIES LLC","WOESTMAN PROP LLC","WOLFF, MICHAEL","WOODLEY BUILDING MAINTENANCE","WOODYS TIRE-AUTO & TOWING LLC","WORLD WIDE TECHNOLOGY INC","WRIGHT EXPRESS FINANCIAL","WRIGHT-JONES, ROBIN","WUNDERLICH, JAMES KEVIN","WW GRAINGER","WW GRAINGER INC","WW GRAINGER-KANSAS CITY","XEROX CORPORATION","XPEDX","XPEDX-COLUMBIA","YOUNGER, MATTHEW W","ZEP SALES & SERVICE","ZOELLNER, KEVIN","ZOLL MEDICAL CORPORATION"];

  var dropDown = d3.select("#filter").append("select")
                    .attr("name", "Vendor sale points");

  var options = dropDown.selectAll("option")
           .data(["All"].concat(ven))
           .enter()
           .append("option");

  options.text(function (d) { return d; })
       .attr("value", function (d) { return d; });
 
  updateScales('Agency');
  var pointColour = d3.scale.category20b();
  d3.select('svg g.chart')
    .selectAll('circle')
    .data(data)
    .enter()
    .append('circle')
    .attr("class", "circles")
    .attr('cx', function(d) {
      return isNaN(d[xAxis]) ? xScale(d[xAxis]) : xScale(d[xAxis]);
    
    })
    .attr('cy', function(d) {
      return isNaN(d[yAxis]) ? d3.select(this).attr('cy') : yScale(d[yAxis]);
    
    })
    .attr('fill', function(d, i) {return pointColour(i);})
    .style('cursor', 'pointer')
    .on('mouseover', function(d) {
      d3.select('svg g.chart #countryLabel')
        .text( //d.Agency)
          function(c){// console.log(xAxis);
            // console.log(d.Agency);
            // return "mm";})
            if(xAxis == 'Agency') return d.Agency;
                               else if(xAxis == 'Category') return d.Category;
                                return d.Detail;})
        .transition()
        .style('opacity', 1);



        var circle = d3.select(this);

      // transition to increase size/opacity of bubble
      circle.transition()
      .duration(800).style("opacity", 1)
      .attr("r", 16).ease("elastic");

      // append lines to bubbles that will be used to show the precise data points.
      // translate their location based on margins
      //console.log(circle.attr("cx"));
      svg.append("g")
        .attr("class", "guide")
      .append("line")
        .attr("x1", circle.attr("cx"))
        .attr("x2", circle.attr("cx"))
        .attr("y1", +circle.attr("cy") + 20)
        .attr("y2", 670-20)
        .attr("transform", "translate(80,-80)")
        .style("stroke", circle.style("fill"))
        // .transition().delay(200).duration(400).styleTween("opacity", 
        //       function() { return d3.interpolate(0, .5); })

      svg.append("g")
        .attr("class", "guide")
      .append("line")
        .attr("x1", +circle.attr("cx") - 14)
        .attr("x2", -25)
        .attr("y1", circle.attr("cy"))
        .attr("y2", circle.attr("cy"))
        .attr("transform", "translate(95,-61)")
        .style("stroke", circle.style("fill"))
        // .transition().delay(200).duration(400).styleTween("opacity", 
        //       function() { return d3.interpolate(0, .5); });

      // function to move mouseover item to front of SVG stage, in case
      // another bubble overlaps it

      d3.selection.prototype.moveToFront = function() { 
        return this.each(function() { 
        this.parentNode.appendChild(this); 
        }); 
      };
//d3.select(this).moveToFront();
      // skip this functionality for IE9, which doesn't like it
      // if (!$.browser.msie) {
      //   circle.moveToFront(); 
      //   }

      
    })
    .on('mouseout', function(d) {
      d3.select('svg g.chart #countryLabel')
        .transition()
        .duration(1500)
        .style('opacity', 0);
      var circle = d3.select(this);

      // go back to original size and opacity
      circle.transition()
      .duration(800).style("opacity", .5)
      .attr("r", 5).ease("elastic");

      // fade out guide lines, then remove them
      d3.selectAll(".guide").transition().duration(100).styleTween("opacity", 
              function() { return d3.interpolate(.5, 0); })
        .remove()



    })
    .append("title")
      .text(function(d) { return d.Agency; });

  updateChart('Agency');
  updateMenus();
  
  // $(".circles").tipsy({ gravity: 's', });


  // Render axes
  d3.select('svg g.chart')
    .append("g")
    .attr('transform', 'translate(-20, 630)')
    .attr('id', 'xAxis')
    .call(makeXAxis)
    .selectAll("text")  
            .style("text-anchor", "end")
            .attr("dx", "-.8em")
            .attr("dy", ".15em")
            .attr("transform", function(d) {
                return "rotate(-65)" 
                });

  d3.select('svg g.chart')
    .append("g")
    .attr('id', 'yAxis')
    .attr('transform', 'translate(-10, 0)')
    .call(makeYAxis);



  //// RENDERING FUNCTIONS
  function updateChart(init) {
    updateScales(init);

    d3.select('svg g.chart')
      .selectAll('circle')
      .transition()
      .duration(500)
      .ease('quad-out')
      .attr('cx', function(d) {
        return isNaN(d[xAxis]) ? xScale(d[xAxis]) : xScale(d[xAxis]);
      })
      .attr('cy', function(d) {
        return isNaN(d[yAxis]) ? d3.select(this).attr('cy') : yScale(d[yAxis]);
      })
      .attr('r', function(d) {
        // return isNaN(d[xAxis]) || isNaN(d[yAxis]) ? 0 : 12;
        return 5;
      });

    // Also update the axes
 
    //??????????
    d3.select('#xAxis')
     // .transition()
      .call(makeXAxis)
      .selectAll("text")  
            .style("text-anchor", "end")
            .attr("dx", "-.8em")
            .attr("dy", ".15em")
      //           .select(this.parentNode)
            .attr("transform", 
              function(d) {
                //console.log(d);
                return "rotate(-65)" 
                });
    //   d3.select('svg g.chart')
    // .append("g")
    // .attr('transform', 'translate(0, 630)')
    // .attr('id', 'xAxis')
    // .call(makeXAxis)
    // .selectAll("text")  
    //         .style("text-anchor", "end")
    //         .attr("dx", "-.8em")
    //         .attr("dy", ".15em")
    //         .attr("transform", function(d) {
    //             return "rotate(-65)" 
    //             });


    d3.select('#yAxis')
      .transition()
      .call(makeYAxis);

    // Update axis labels
    d3.select('#xLabel')
      .text(descriptions[xAxis]);

    // Update correlation
    var xArray = _.map(data, function(d) {return xScale(d[xAxis]);});
    var yArray = _.map(data, function(d) {return d[yAxis];});
    // console.log(xArray,yArray);
    var c = getCorrelation(xArray, yArray);
    // console.log(c);
    var x1 = xScale(xScale.domain()[0]), y1 = c.m * x1 + c.b;
    var x2 = xScale(xScale.domain()[1]), y2 = c.m * x2 + c.b;

    // Fade in
    // d3.select('#bestfit')
    //   .style('opacity', 0)
    //   .attr({'x1': x1, 'y1': yScale(y1), 'x2': x2, 'y2': yScale(y2)})
    //   .transition()
    //   .duration(1500)
    //   .style('opacity', 1);
  }

  function updateScales(ss) {
    // xScale = d3.scale.linear()
    //                 .domain([bounds[xAxis].min, bounds[xAxis].max])
    //                 .range([20, 780]);
    xScale = d3.scale.ordinal()
                    .rangeRoundBands([0, 800], 0.1)
          if(ss==='Agency'){
              
                    xScale.domain(agen.map(function(d) {return d; })); 
      }else if(ss==='Category'){

                    xScale.domain(cate.map(function(d) {return d; })); 
      }else if(ss==='Detail'){

                    xScale.domain(det.map(function(d) {return d; })); 
      }
    // xScale = d3.scale.ordinal()
    //                 .rangeRoundBands([0, 700], 0.1)
    //                 .domain(agen.map(function(d) {return d; }));             

    yScale = d3.scale.log()
                    .domain([bounds[yAxis].min, bounds[yAxis].max])
                    .range([600, 100]);    
  }

  function makeXAxis(s) {
    s.call(d3.svg.axis()
      .scale(xScale)
      .orient("bottom"));
  }

  function makeYAxis(s) {
    s.call(d3.svg.axis()
      .scale(yScale)
      .orient("left"));
  }

  function updateMenus() {
    d3.select('#x-axis-menu')
      .selectAll('li')
      .classed('selected', function(d) {
        return d === xAxis;
      });
    d3.select('#y-axis-menu')
      .selectAll('li')
      .classed('selected', function(d) {
        return d === yAxis;
    });
  }

    dropDown.on("change", function() {
      var selected = this.value;
      console.log(selected);
      displayOthers = this.checked ? "inline" : "none";
      console.log(displayOthers);
      display = this.checked ? "none" : "inline";
      console.log(display);
      if(selected == 'All'){
        svg.selectAll(".circles")
            .attr("display", display);
      }
      else{
        svg.selectAll(".circles")
            .filter(function(d) {return selected != d.Vendor;})
            .attr("display", displayOthers);
            
        svg.selectAll(".circles")
            .filter(function(d) {return selected == d.Vendor;})
            .attr("display", display);
      }
  });

})


